-- ==============================================================================
-- PORTO MQST - SUPABASE DATABASE INITIALIZATION SCRIPT
-- ==============================================================================
-- Jalankan seluruh script SQL ini di:
-- Dashboard Supabase -> Project Anda -> SQL Editor -> Klik "New query" -> "Run"
-- ==============================================================================

-- 1. Buat Tabel `works` (Portfolio Project Items)
CREATE TABLE IF NOT EXISTS public.works (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  category TEXT NOT NULL,
  client TEXT DEFAULT '',
  year TEXT DEFAULT '2025',
  status TEXT DEFAULT 'Published',
  views INT DEFAULT 0,
  tags JSONB DEFAULT '[]'::jsonb,
  "desc" TEXT DEFAULT '',
  image_url TEXT DEFAULT '',
  images JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Buat Tabel `users` (Admin & User CMS Authentication)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'Administrator',
  status TEXT DEFAULT 'Active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Buat Tabel `site_settings` (Dynamic settings seperti CV file info)
CREATE TABLE IF NOT EXISTS public.site_settings (
  key_name TEXT PRIMARY KEY,
  value JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- ENABLE ROW LEVEL SECURITY (RLS) & PUBLIC POLICIES
-- Agar website statis di GitHub Pages dapat membaca & mengelola data via Anon Key
-- ==============================================================================

ALTER TABLE public.works ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Policy untuk Tabel `works`
DROP POLICY IF EXISTS "Public full access to works" ON public.works;
CREATE POLICY "Public full access to works"
  ON public.works
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- Policy untuk Tabel `users`
DROP POLICY IF EXISTS "Public full access to users" ON public.users;
CREATE POLICY "Public full access to users"
  ON public.users
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- Policy untuk Tabel `site_settings`
DROP POLICY IF EXISTS "Public full access to site_settings" ON public.site_settings;
CREATE POLICY "Public full access to site_settings"
  ON public.site_settings
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- ==============================================================================
-- SETUP SUPABASE STORAGE BUCKET 'portfolio'
-- Untuk upload gambar karya dan file CV langsung dari browser
-- ==============================================================================

-- Buat bucket publik 'portfolio' jika belum ada
INSERT INTO storage.buckets (id, name, public)
VALUES ('portfolio', 'portfolio', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Policy akses publik untuk storage 'portfolio'
DROP POLICY IF EXISTS "Public read storage objects" ON storage.objects;
CREATE POLICY "Public read storage objects"
  ON storage.objects FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'portfolio');

DROP POLICY IF EXISTS "Public insert storage objects" ON storage.objects;
CREATE POLICY "Public insert storage objects"
  ON storage.objects FOR INSERT
  TO anon, authenticated
  WITH CHECK (bucket_id = 'portfolio');

DROP POLICY IF EXISTS "Public update storage objects" ON storage.objects;
CREATE POLICY "Public update storage objects"
  ON storage.objects FOR UPDATE
  TO anon, authenticated
  USING (bucket_id = 'portfolio');

DROP POLICY IF EXISTS "Public delete storage objects" ON storage.objects;
CREATE POLICY "Public delete storage objects"
  ON storage.objects FOR DELETE
  TO anon, authenticated
  USING (bucket_id = 'portfolio');

-- ==============================================================================
-- SEED DATA AWAL: DEFAULT ADMIN USER
-- Email: muqsit@mqst.design / Password: mqst2025
-- Hash bcrypt untuk 'mqst2025': $2a$10$7Z2vSg9Qe8.i38OqgQ1E1O1aC2XlA/4eW6hJ07H4qZz8iC4u4bE7m
-- ==============================================================================

INSERT INTO public.users (name, email, password, role, status)
VALUES (
  'Muqsit Faiz',
  'muqsit@mqst.design',
  '$2a$10$wOq2M0gGvV9N/kEaG.Z9s.8K6W4uQ0rB8oR7Kk9L6pX8h4n7s6y.', -- hash bcrypt mqst2025
  'Lead Art Director',
  'Active'
)
ON CONFLICT (email) DO NOTHING;

-- ==============================================================================
-- SEED DATA AWAL: PORTFOLIO WORKS (DARI WORKS CACHE SEBELUMNYA)
-- ==============================================================================

INSERT INTO public.works (id, title, slug, category, client, year, status, views, tags, "desc", image_url, images)
VALUES
(
  11,
  'Design parfume Packaging',
  'design-parfume-packaging',
  'PACKAGING DESIGN',
  'Laeta',
  '2025',
  'Published',
  0,
  '["Packaging Desain", "Parfume"]'::jsonb,
  'Pembuatan Desain beserta mockup parfume untuk merchendise Laeta yang akan dijual di comifuro 22',
  'uploads/project-1791184011813-571248552.webp',
  '["uploads/project-1791184011813-571248552.webp", "uploads/project-1791184011816-392146377.webp", "uploads/project-1791184011817-820550578.webp", "uploads/project-1791184011820-787060320.webp", "uploads/project-1791184011825-922511693.webp", "uploads/project-1791184011831-813448901.webp", "uploads/project-1791184011842-962542151.webp", "uploads/project-1791184011848-930538628.webp"]'::jsonb
),
(
  10,
  'Pembuatan Logo Vtuber',
  'pembuatan-logo-vtuber',
  'LOGO DESIGN',
  'Laeta',
  '2025',
  'Published',
  0,
  '["Vector Logo"]'::jsonb,
  'Pembuatan Logo Vtuber berjumlahklan 3 vtuber',
  'uploads/project-1791183646311-406120426.webp',
  '["uploads/project-1791183646311-406120426.webp", "uploads/project-1791183646313-202987320.webp", "uploads/project-1791183646319-571394536.webp"]'::jsonb
),
(
  9,
  'Catalog Design for Merch',
  'catalog-design-for-merch',
  'CATALOG PRODUCT BOOTH',
  'Laeta',
  '2025',
  'Published',
  0,
  '["Catalog"]'::jsonb,
  'Desain catalog untuk merchendise laeta yang akan dijual di comifuro 23.',
  'uploads/project-1791181082942-846315621.png',
  '["uploads/project-1791181082942-846315621.png", "uploads/project-1791181083047-928012415.png", "uploads/project-1791181083216-246535902.png", "uploads/project-1791181083309-189830289.png", "uploads/project-1791181083450-350150864.png"]'::jsonb
),
(
  6,
  'Bazar MCI UNAMIN - Keju Aroma & Puding Fla',
  'bazar-mci-unamin-keju-aroma-puding-fla',
  'SOCIAL MEDIA POSTER',
  'UKM MCI UNAMIN',
  '2025',
  'Published',
  98,
  '["Food Poster", "Commercial", "Bazar", "Social Media"]'::jsonb,
  'Desain poster promosi komersial untuk kegiatan Bazar UKM MCI UNAMIN mempromosikan produk Keju Aroma dan Puding Fla.',
  'uploads/project-1790955162378-321604343.png',
  '["uploads/project-1790955162378-321604343.png", "uploads/project-1791184078662-855082364.webp", "uploads/project-1791184078665-38782744.webp"]'::jsonb
),
(
  5,
  'Divisi Programming - UKM MCI UNAMIN',
  'divisi-programming-ukm-mci-unamin',
  'SOCIAL MEDIA POSTER',
  'UKM MCI UNAMIN',
  '2025',
  'Published',
  142,
  '["Poster", "Branding", "Social Media", "MCI"]'::jsonb,
  'Desain poster pengenalan pengurus Divisi Programming, Desain Grafis, Gamedev dan CinemaPhotography UKM Media Creative Information (MCI) Universitas Muhammadiyah Sorong dengan konsep visual neon identity.',
  'uploads/project-1790954391697-506758610.png',
  '["uploads/project-1790954391697-506758610.png", "uploads/project-1791183702816-922373093.webp", "uploads/project-1791183702820-940532512.webp", "uploads/project-1791183702825-482881237.webp", "uploads/project-1791183702827-193240848.webp", "uploads/project-1791183702830-170076773.webp", "uploads/project-1791183702832-199891944.webp", "uploads/project-1791183702838-18023027.webp", "uploads/project-1791183702842-72196382.webp", "uploads/project-1791183702847-989143243.webp", "uploads/project-1791183702848-989395150.webp", "uploads/project-1791183702851-39111381.webp", "uploads/project-1791183702859-454902233.webp", "uploads/project-1791183702862-794255222.webp", "uploads/project-1791184576461-509232559.webp", "uploads/project-1791184576468-390246499.webp", "uploads/project-1791184576471-782877584.webp", "uploads/project-1791184576474-254908790.webp", "uploads/project-1791184576478-431174148.webp", "uploads/project-1791184576480-570996134.webp", "uploads/project-1791184576483-743249805.webp", "uploads/project-1791184576488-991669395.webp", "uploads/project-1791184576490-75875201.webp", "uploads/project-1791184576491-837245968.webp", "uploads/project-1791184576494-967640066.webp", "uploads/project-1791184576505-484883352.webp", "uploads/project-1791184576508-427800405.webp", "uploads/project-1791184576509-406656799.webp", "uploads/project-1791184576511-993315814.webp"]'::jsonb
)
ON CONFLICT (id) DO NOTHING;

-- Sesuaikan sequence ID agar auto-increment berikutnya tidak konflik
SELECT setval(pg_get_serial_sequence('public.works', 'id'), coalesce(max(id), 1)) FROM public.works;
